### PR TITLE
Add  pulse audio detection for Linux

### PR DESCRIPTION
**Pull request by bkram**
Add  pulse audio detection for Linux

### CODE REVIEW

**Comment by NoobishSVK** [comment]
Thanks for the pull request, I will merge it as soon as i'm done with the admin panel to prevent merge conflicts.

**Comment by NoobishSVK** [comment]
Sadly there are conflict, is it possible to fix this? There's also a new file for parsing (stream/parser.js)

**Comment by bkram** [comment]
With the latest release also the audio devices should detected and be select-able, when I have time I will try to add that to the PR too.

**Comment by NoobishSVK** [comment]
OK. Would it be better for you if I close dthis PR so you can make a new one or willl you edit this one?

**Comment by bkram** [comment]
Agreed, let's close this one.

**Pull request closed without merging**
